### ISSUE TITLE
Add description on what Leetcode is for people who haven't heard of it, linking the site.

### ISSUE THREAD

**Issue by KendallDoesCoding** [collab-community/Leetcode-problem#2]
Add description on what Leetcode is for people who haven't heard of it, linking the site in README.md

@Abhinavkar - can you do this?

**Comment by saksham5701** [comment]
do you want to add some heading of what leetcode is all about?

**Comment by KendallDoesCoding** [comment]
> do you want to add some heading of what leetcode is all about?

yes

**Comment by Abhinavkar** [comment]
@saksham5701 Should i Assign you ?

**Comment by saksham5701** [comment]
> @saksham5701 Should I Assign you ?

Yes,I actually wanted to get started with open source so I tried to solve this good first issue.

**Comment by omogidi** [comment]
Starting my journey in open source.

**Comment by SandeepUrankar** [comment]
Hey, if it is not assigned to anyone yet. You can assign me. I can make that work done. Have been practicing problem on Leetcode myself.

**Comment by KendallDoesCoding** [comment]
> Starting my journey in open source.

Please refer to [Journey Book](https://github.com/collab-community/journey-book) for that.

**Comment by KendallDoesCoding** [comment]
> Hey, if it is not assigned to anyone yet. You can assign me. I can make that work done. Have been practicing problem on Leetcode myself.

Hi, It's actually assigned to @saksham5701 as he requested to work on it, before you, but you can help them if they are finding any difficulty.

You can contribute to this repo in other ways or check out our other repo's and their issues and contribute to them! Thanks

**Comment by SandeepUrankar** [comment]
> > Hey, if it is not assigned to anyone yet. You can assign me. I can make that work done. Have been practicing problem on Leetcode myself.
> 
> Hi, It's actually assigned to @saksham5701 as he requested to work on it, before you, but you can help them if they are finding any difficulty.
> 
> You can contribute to this repo in other ways or check out our other repo's and their issues and contribute to them! Thanks

Yep will do.
