### ISSUE TITLE
[DOCS] Add CONTRIBUTING GUIDELINES

### ISSUE THREAD

**Issue by KendallDoesCoding** [collab-community/Leetcode-problem#4]
Add contributing guidelines.

**Comment by fk00750** [comment]
Hey can you assign me this issue?

**Comment by KendallDoesCoding** [comment]
> Hey can you assign me this issue?

Done!

**Comment by KendallDoesCoding** [comment]
@Abhinavkar please provide @fk00750 with any details if required by them.
